model itelogisticModel.mod;
data zDDM_PTVHD_5.dat;
data zDDM_PTVHD_105.dat;
data zDDM_PTVHD_185.dat;
data zDDM_PTVHD_230.dat;
data zDDM_PTVHD_310.dat;
data ite_MapVoxel_PTVHD.dat;
data zDDM_RECTUM_5.dat;
data zDDM_RECTUM_105.dat;
data zDDM_RECTUM_185.dat;
data zDDM_RECTUM_230.dat;
data zDDM_RECTUM_310.dat;
data ite_MapVoxel_RECTUM.dat;
data zDDM_BLADDER_5.dat;
data zDDM_BLADDER_105.dat;
data zDDM_BLADDER_185.dat;
data zDDM_BLADDER_230.dat;
data zDDM_BLADDER_310.dat;
data ite_MapVoxel_BLADDER.dat;
data iteextraLogFunction.dat;
solve;
display x5 > itecurrentSol_5.txt;
display x105 > itecurrentSol_105.txt;
display x185 > itecurrentSol_185.txt;
display x230 > itecurrentSol_230.txt;
display x310 > itecurrentSol_310.txt;
display ( ((1/R_PTVHD)*(sum {i in voxelIndex_PTVHD}( (sum {j in bmltsIndex_PTVHD_5: (i,j) in voxelbmlt_PTVHD_5} x5[j]*intensities_PTVHD_5[i,j]) +(sum {j in bmltsIndex_PTVHD_105: (i,j) in voxelbmlt_PTVHD_105} x105[j]*intensities_PTVHD_105[i,j]) +(sum {j in bmltsIndex_PTVHD_185: (i,j) in voxelbmlt_PTVHD_185} x185[j]*intensities_PTVHD_185[i,j]) +(sum {j in bmltsIndex_PTVHD_230: (i,j) in voxelbmlt_PTVHD_230} x230[j]*intensities_PTVHD_230[i,j]) +(sum {j in bmltsIndex_PTVHD_310: (i,j) in voxelbmlt_PTVHD_310} x310[j]*intensities_PTVHD_310[i,j]) )^a[1])))^(1/a[1]) > itegEUD_PTVHD.txt;
 display {i in 1 .. R_PTVHD} (sum {j in bmltsIndex_PTVHD_5: (i,j) in voxelbmlt_PTVHD_5} x5[j]*intensities_PTVHD_5[i,j]) +(sum {j in bmltsIndex_PTVHD_105: (i,j) in voxelbmlt_PTVHD_105} x105[j]*intensities_PTVHD_105[i,j]) +(sum {j in bmltsIndex_PTVHD_185: (i,j) in voxelbmlt_PTVHD_185} x185[j]*intensities_PTVHD_185[i,j]) +(sum {j in bmltsIndex_PTVHD_230: (i,j) in voxelbmlt_PTVHD_230} x230[j]*intensities_PTVHD_230[i,j]) +(sum {j in bmltsIndex_PTVHD_310: (i,j) in voxelbmlt_PTVHD_310} x310[j]*intensities_PTVHD_310[i,j])  > iteDVH_PTVHD.txt;
display (((1/R_PTVHD)*(sum {i in voxelIndex_PTVHD} ((sum{j in bmltsIndex_PTVHD_5: (i,j) in voxelbmlt_PTVHD_5} x5[j]*intensities_PTVHD_5[i,j]) +(sum{j in bmltsIndex_PTVHD_105: (i,j) in voxelbmlt_PTVHD_105} x105[j]*intensities_PTVHD_105[i,j]) +(sum{j in bmltsIndex_PTVHD_185: (i,j) in voxelbmlt_PTVHD_185} x185[j]*intensities_PTVHD_185[i,j]) +(sum{j in bmltsIndex_PTVHD_230: (i,j) in voxelbmlt_PTVHD_230} x230[j]*intensities_PTVHD_230[i,j]) +(sum{j in bmltsIndex_PTVHD_310: (i,j) in voxelbmlt_PTVHD_310} x310[j]*intensities_PTVHD_310[i,j]) )^a[4])))^(1/a[4]) > itegEUD_PTVHD_UB.txt;
display ( ((1/R_RECTUM)*(sum {i in voxelIndex_RECTUM}( (sum {j in bmltsIndex_RECTUM_5: (i,j) in voxelbmlt_RECTUM_5} x5[j]*intensities_RECTUM_5[i,j]) +(sum {j in bmltsIndex_RECTUM_105: (i,j) in voxelbmlt_RECTUM_105} x105[j]*intensities_RECTUM_105[i,j]) +(sum {j in bmltsIndex_RECTUM_185: (i,j) in voxelbmlt_RECTUM_185} x185[j]*intensities_RECTUM_185[i,j]) +(sum {j in bmltsIndex_RECTUM_230: (i,j) in voxelbmlt_RECTUM_230} x230[j]*intensities_RECTUM_230[i,j]) +(sum {j in bmltsIndex_RECTUM_310: (i,j) in voxelbmlt_RECTUM_310} x310[j]*intensities_RECTUM_310[i,j]) )^a[2])))^(1/a[2]) > itegEUD_RECTUM.txt;
 display {i in 1 .. R_RECTUM} (sum {j in bmltsIndex_RECTUM_5: (i,j) in voxelbmlt_RECTUM_5} x5[j]*intensities_RECTUM_5[i,j]) +(sum {j in bmltsIndex_RECTUM_105: (i,j) in voxelbmlt_RECTUM_105} x105[j]*intensities_RECTUM_105[i,j]) +(sum {j in bmltsIndex_RECTUM_185: (i,j) in voxelbmlt_RECTUM_185} x185[j]*intensities_RECTUM_185[i,j]) +(sum {j in bmltsIndex_RECTUM_230: (i,j) in voxelbmlt_RECTUM_230} x230[j]*intensities_RECTUM_230[i,j]) +(sum {j in bmltsIndex_RECTUM_310: (i,j) in voxelbmlt_RECTUM_310} x310[j]*intensities_RECTUM_310[i,j])  > iteDVH_RECTUM.txt;
display ( ((1/R_BLADDER)*(sum {i in voxelIndex_BLADDER}( (sum {j in bmltsIndex_BLADDER_5: (i,j) in voxelbmlt_BLADDER_5} x5[j]*intensities_BLADDER_5[i,j]) +(sum {j in bmltsIndex_BLADDER_105: (i,j) in voxelbmlt_BLADDER_105} x105[j]*intensities_BLADDER_105[i,j]) +(sum {j in bmltsIndex_BLADDER_185: (i,j) in voxelbmlt_BLADDER_185} x185[j]*intensities_BLADDER_185[i,j]) +(sum {j in bmltsIndex_BLADDER_230: (i,j) in voxelbmlt_BLADDER_230} x230[j]*intensities_BLADDER_230[i,j]) +(sum {j in bmltsIndex_BLADDER_310: (i,j) in voxelbmlt_BLADDER_310} x310[j]*intensities_BLADDER_310[i,j]) )^a[3])))^(1/a[3]) > itegEUD_BLADDER.txt;
 display {i in 1 .. R_BLADDER} (sum {j in bmltsIndex_BLADDER_5: (i,j) in voxelbmlt_BLADDER_5} x5[j]*intensities_BLADDER_5[i,j]) +(sum {j in bmltsIndex_BLADDER_105: (i,j) in voxelbmlt_BLADDER_105} x105[j]*intensities_BLADDER_105[i,j]) +(sum {j in bmltsIndex_BLADDER_185: (i,j) in voxelbmlt_BLADDER_185} x185[j]*intensities_BLADDER_185[i,j]) +(sum {j in bmltsIndex_BLADDER_230: (i,j) in voxelbmlt_BLADDER_230} x230[j]*intensities_BLADDER_230[i,j]) +(sum {j in bmltsIndex_BLADDER_310: (i,j) in voxelbmlt_BLADDER_310} x310[j]*intensities_BLADDER_310[i,j])  > iteDVH_BLADDER.txt;
