model testlogisticModel.mod;
data zDDM_PTVHD_45.dat;
data zDDM_PTVHD_145.dat;
data zDDM_PTVHD_210.dat;
data zDDM_PTVHD_220.dat;
data zDDM_PTVHD_325.dat;
data test_MapVoxel_PTVHD.dat;
data zDDM_RECTUM_45.dat;
data zDDM_RECTUM_145.dat;
data zDDM_RECTUM_210.dat;
data zDDM_RECTUM_220.dat;
data zDDM_RECTUM_325.dat;
data test_MapVoxel_RECTUM.dat;
data zDDM_BLADDER_45.dat;
data zDDM_BLADDER_145.dat;
data zDDM_BLADDER_210.dat;
data zDDM_BLADDER_220.dat;
data zDDM_BLADDER_325.dat;
data test_MapVoxel_BLADDER.dat;
data testextraLogFunction.dat;
solve;
display x45 > testcurrentSol_45.txt;
display x145 > testcurrentSol_145.txt;
display x210 > testcurrentSol_210.txt;
display x220 > testcurrentSol_220.txt;
display x325 > testcurrentSol_325.txt;
display ( ((1/R_PTVHD)*(sum {i in voxelIndex_PTVHD}( (sum {j in bmltsIndex_PTVHD_45: (i,j) in voxelbmlt_PTVHD_45} x45[j]*intensities_PTVHD_45[i,j]) +(sum {j in bmltsIndex_PTVHD_145: (i,j) in voxelbmlt_PTVHD_145} x145[j]*intensities_PTVHD_145[i,j]) +(sum {j in bmltsIndex_PTVHD_210: (i,j) in voxelbmlt_PTVHD_210} x210[j]*intensities_PTVHD_210[i,j]) +(sum {j in bmltsIndex_PTVHD_220: (i,j) in voxelbmlt_PTVHD_220} x220[j]*intensities_PTVHD_220[i,j]) +(sum {j in bmltsIndex_PTVHD_325: (i,j) in voxelbmlt_PTVHD_325} x325[j]*intensities_PTVHD_325[i,j]) )^a[1])))^(1/a[1]) > testgEUD_PTVHD.txt;
 display {i in 1 .. R_PTVHD} (sum {j in bmltsIndex_PTVHD_45: (i,j) in voxelbmlt_PTVHD_45} x45[j]*intensities_PTVHD_45[i,j]) +(sum {j in bmltsIndex_PTVHD_145: (i,j) in voxelbmlt_PTVHD_145} x145[j]*intensities_PTVHD_145[i,j]) +(sum {j in bmltsIndex_PTVHD_210: (i,j) in voxelbmlt_PTVHD_210} x210[j]*intensities_PTVHD_210[i,j]) +(sum {j in bmltsIndex_PTVHD_220: (i,j) in voxelbmlt_PTVHD_220} x220[j]*intensities_PTVHD_220[i,j]) +(sum {j in bmltsIndex_PTVHD_325: (i,j) in voxelbmlt_PTVHD_325} x325[j]*intensities_PTVHD_325[i,j])  > testDVH_PTVHD.txt;
display (((1/R_PTVHD)*(sum {i in voxelIndex_PTVHD} ((sum{j in bmltsIndex_PTVHD_45: (i,j) in voxelbmlt_PTVHD_45} x45[j]*intensities_PTVHD_45[i,j]) +(sum{j in bmltsIndex_PTVHD_145: (i,j) in voxelbmlt_PTVHD_145} x145[j]*intensities_PTVHD_145[i,j]) +(sum{j in bmltsIndex_PTVHD_210: (i,j) in voxelbmlt_PTVHD_210} x210[j]*intensities_PTVHD_210[i,j]) +(sum{j in bmltsIndex_PTVHD_220: (i,j) in voxelbmlt_PTVHD_220} x220[j]*intensities_PTVHD_220[i,j]) +(sum{j in bmltsIndex_PTVHD_325: (i,j) in voxelbmlt_PTVHD_325} x325[j]*intensities_PTVHD_325[i,j]) )^a[4])))^(1/a[4]) > testgEUD_PTVHD_UB.txt;
display ( ((1/R_RECTUM)*(sum {i in voxelIndex_RECTUM}( (sum {j in bmltsIndex_RECTUM_45: (i,j) in voxelbmlt_RECTUM_45} x45[j]*intensities_RECTUM_45[i,j]) +(sum {j in bmltsIndex_RECTUM_145: (i,j) in voxelbmlt_RECTUM_145} x145[j]*intensities_RECTUM_145[i,j]) +(sum {j in bmltsIndex_RECTUM_210: (i,j) in voxelbmlt_RECTUM_210} x210[j]*intensities_RECTUM_210[i,j]) +(sum {j in bmltsIndex_RECTUM_220: (i,j) in voxelbmlt_RECTUM_220} x220[j]*intensities_RECTUM_220[i,j]) +(sum {j in bmltsIndex_RECTUM_325: (i,j) in voxelbmlt_RECTUM_325} x325[j]*intensities_RECTUM_325[i,j]) )^a[2])))^(1/a[2]) > testgEUD_RECTUM.txt;
 display {i in 1 .. R_RECTUM} (sum {j in bmltsIndex_RECTUM_45: (i,j) in voxelbmlt_RECTUM_45} x45[j]*intensities_RECTUM_45[i,j]) +(sum {j in bmltsIndex_RECTUM_145: (i,j) in voxelbmlt_RECTUM_145} x145[j]*intensities_RECTUM_145[i,j]) +(sum {j in bmltsIndex_RECTUM_210: (i,j) in voxelbmlt_RECTUM_210} x210[j]*intensities_RECTUM_210[i,j]) +(sum {j in bmltsIndex_RECTUM_220: (i,j) in voxelbmlt_RECTUM_220} x220[j]*intensities_RECTUM_220[i,j]) +(sum {j in bmltsIndex_RECTUM_325: (i,j) in voxelbmlt_RECTUM_325} x325[j]*intensities_RECTUM_325[i,j])  > testDVH_RECTUM.txt;
display ( ((1/R_BLADDER)*(sum {i in voxelIndex_BLADDER}( (sum {j in bmltsIndex_BLADDER_45: (i,j) in voxelbmlt_BLADDER_45} x45[j]*intensities_BLADDER_45[i,j]) +(sum {j in bmltsIndex_BLADDER_145: (i,j) in voxelbmlt_BLADDER_145} x145[j]*intensities_BLADDER_145[i,j]) +(sum {j in bmltsIndex_BLADDER_210: (i,j) in voxelbmlt_BLADDER_210} x210[j]*intensities_BLADDER_210[i,j]) +(sum {j in bmltsIndex_BLADDER_220: (i,j) in voxelbmlt_BLADDER_220} x220[j]*intensities_BLADDER_220[i,j]) +(sum {j in bmltsIndex_BLADDER_325: (i,j) in voxelbmlt_BLADDER_325} x325[j]*intensities_BLADDER_325[i,j]) )^a[3])))^(1/a[3]) > testgEUD_BLADDER.txt;
 display {i in 1 .. R_BLADDER} (sum {j in bmltsIndex_BLADDER_45: (i,j) in voxelbmlt_BLADDER_45} x45[j]*intensities_BLADDER_45[i,j]) +(sum {j in bmltsIndex_BLADDER_145: (i,j) in voxelbmlt_BLADDER_145} x145[j]*intensities_BLADDER_145[i,j]) +(sum {j in bmltsIndex_BLADDER_210: (i,j) in voxelbmlt_BLADDER_210} x210[j]*intensities_BLADDER_210[i,j]) +(sum {j in bmltsIndex_BLADDER_220: (i,j) in voxelbmlt_BLADDER_220} x220[j]*intensities_BLADDER_220[i,j]) +(sum {j in bmltsIndex_BLADDER_325: (i,j) in voxelbmlt_BLADDER_325} x325[j]*intensities_BLADDER_325[i,j])  > testDVH_BLADDER.txt;
